<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NUCLEAR_OPTION_SERVER_REFERENCES>C:\Program Files\Steam\steamapps\common\Nuclear Option\NuclearOption_Data\Managed</NUCLEAR_OPTION_SERVER_REFERENCES>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <ModDestination>$(NUCLEAR_OPTION_SERVER_REFERENCES)\..\..\BepInEx\plugins</ModDestination>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>C:\Program Files\Steam\steamapps\common\Nuclear Option\BepInEx\core\BepInEx.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>C:\Program Files\Steam\steamapps\common\Nuclear Option\BepInEx\core\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="UnityEngine">
      <HintPath>$(NUCLEAR_OPTION_SERVER_REFERENCES)\UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(NUCLEAR_OPTION_SERVER_REFERENCES)\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(NUCLEAR_OPTION_SERVER_REFERENCES)\UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(NUCLEAR_OPTION_SERVER_REFERENCES)\UnityEngine.UIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>$(NUCLEAR_OPTION_SERVER_REFERENCES)\UnityEngine.VideoModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(NUCLEAR_OPTION_SERVER_REFERENCES)\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(NUCLEAR_OPTION_SERVER_REFERENCES)\UnityEngine.AudioModule.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath>$(NUCLEAR_OPTION_SERVER_REFERENCES)\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="MainMenuReplacer.cs" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="Build" Condition="'$(ModDestination)' != ''">
    <Message Text="Copying $(TargetFileName) directly to $(ModDestination)" Importance="high" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModDestination)" />
  </Target>
</Project>
